/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author cybergato
 */
public class AgregarData extends javax.swing.JFrame {

    /**
     * Creates new form AgregarData
     */
    public AgregarData() {

        initComponents();

        tf_codigoS.setBorder(javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED,
                new java.awt.Color(105, 58, 128),
                new java.awt.Color(70, 40, 100)));

        tf_precioS.setBorder(javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED,
                new java.awt.Color(105, 58, 128),
                new java.awt.Color(70, 40, 100)));

        tf_productoraS.setBorder(javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED,
                new java.awt.Color(105, 58, 128),
                new java.awt.Color(70, 40, 100)));

        ta_actoresS.setBorder(javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED,
                new java.awt.Color(105, 58, 128),
                new java.awt.Color(70, 40, 100)));

        tf_codigoC.setBorder(javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED,
                new java.awt.Color(105, 58, 128),
                new java.awt.Color(70, 40, 100)));

        tf_precioC.setBorder(javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED,
                new java.awt.Color(105, 58, 128),
                new java.awt.Color(70, 40, 100)));

        tf_nombreC.setBorder(javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED,
                new java.awt.Color(105, 58, 128),
                new java.awt.Color(70, 40, 100)));

        tf_artistaC.setBorder(javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED,
                new java.awt.Color(105, 58, 128),
                new java.awt.Color(70, 40, 100)));

        tf_duracionC.setBorder(javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED,
                new java.awt.Color(105, 58, 128),
                new java.awt.Color(70, 40, 100)));

        tf_nombreP.setBorder(javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED,
                new java.awt.Color(105, 58, 128),
                new java.awt.Color(70, 40, 100)));

        tf_codigoP.setBorder(javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED,
                new java.awt.Color(105, 58, 128),
                new java.awt.Color(70, 40, 100)));

        tf_precioP.setBorder(javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED,
                new java.awt.Color(105, 58, 128),
                new java.awt.Color(70, 40, 100)));

        tf_directorP.setBorder(javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED,
                new java.awt.Color(105, 58, 128),
                new java.awt.Color(70, 40, 100)));

        ta_actoresP.setBorder(javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED,
                new java.awt.Color(105, 58, 128),
                new java.awt.Color(70, 40, 100)));

        tf_duracionP.setBorder(javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED,
                new java.awt.Color(105, 58, 128),
                new java.awt.Color(70, 40, 100)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jp_series = new javax.swing.JPanel();
        hobitoSeries = new javax.swing.JLabel();
        jl_generoS = new javax.swing.JLabel();
        tf_codigoS = new javax.swing.JTextField();
        js_añoS = new javax.swing.JSpinner();
        tf_precioS = new javax.swing.JTextField();
        jc_generoS = new javax.swing.JComboBox<>();
        jl_StockS = new javax.swing.JLabel();
        js_cantStockS = new javax.swing.JSpinner();
        jb_añoS = new javax.swing.JLabel();
        jl_tituloS = new javax.swing.JLabel();
        jl_precioVentaS = new javax.swing.JLabel();
        jl_codigoS = new javax.swing.JLabel();
        tf_nombreS = new javax.swing.JTextField();
        jl_temporadasS = new javax.swing.JLabel();
        js_temporadasS = new javax.swing.JSpinner();
        jl_productoraS = new javax.swing.JLabel();
        js_capitulosS = new javax.swing.JSpinner();
        jl_capitulosS = new javax.swing.JLabel();
        tf_productoraS = new javax.swing.JTextField();
        jl_actoresS = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_actoresS = new javax.swing.JTextArea();
        jb_CancelarS = new javax.swing.JButton();
        jb_LimparS = new javax.swing.JButton();
        jb_GuardarS = new javax.swing.JButton();
        jp_canciones = new javax.swing.JPanel();
        hobitoCanciones = new javax.swing.JLabel();
        jl_generoC = new javax.swing.JLabel();
        tf_codigoC = new javax.swing.JTextField();
        js_añoC = new javax.swing.JSpinner();
        tf_precioC = new javax.swing.JTextField();
        jc_generoC = new javax.swing.JComboBox<>();
        jl_StockC = new javax.swing.JLabel();
        js_noPistaC = new javax.swing.JSpinner();
        jb_añoC = new javax.swing.JLabel();
        jl_tituloC = new javax.swing.JLabel();
        jl_codigoC = new javax.swing.JLabel();
        jl_precioVentaC = new javax.swing.JLabel();
        tf_nombreC = new javax.swing.JTextField();
        jl_artistaC = new javax.swing.JLabel();
        tf_artistaC = new javax.swing.JTextField();
        jl_duracionC = new javax.swing.JLabel();
        tf_duracionC = new javax.swing.JTextField();
        jl_noPistaC = new javax.swing.JLabel();
        js_cantStockC = new javax.swing.JSpinner();
        jb_GuardarC = new javax.swing.JButton();
        jb_LimparC = new javax.swing.JButton();
        jb_CancelarC = new javax.swing.JButton();
        jp_peliculas = new javax.swing.JPanel();
        hobitoPeliculas = new javax.swing.JLabel();
        jl_tituloP = new javax.swing.JLabel();
        jl_codigoP = new javax.swing.JLabel();
        jl_generoP = new javax.swing.JLabel();
        js_añoP = new javax.swing.JSpinner();
        jc_generoP = new javax.swing.JComboBox<>();
        jb_añoP = new javax.swing.JLabel();
        jl_precioVentaP = new javax.swing.JLabel();
        tf_nombreP = new javax.swing.JTextField();
        tf_codigoP = new javax.swing.JTextField();
        tf_precioP = new javax.swing.JTextField();
        jl_StockP = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jl_DirectorP = new javax.swing.JLabel();
        tf_directorP = new javax.swing.JTextField();
        jl_actoresP = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_actoresP = new javax.swing.JTextArea();
        jl_duracionP = new javax.swing.JLabel();
        tf_duracionP = new javax.swing.JTextField();
        jb_LimparP = new javax.swing.JButton();
        jb_GuardarP = new javax.swing.JButton();
        jb_CancelarP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(96, 39, 125));
        jTabbedPane1.setForeground(new java.awt.Color(238, 229, 242));
        jTabbedPane1.setFont(new java.awt.Font("Fredoka", 1, 13)); // NOI18N

        jp_series.setBackground(new java.awt.Color(238, 229, 242));
        jp_series.setForeground(new java.awt.Color(105, 58, 128));

        jl_generoS.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_generoS.setForeground(new java.awt.Color(96, 39, 125));
        jl_generoS.setText("Genero:");

        tf_codigoS.setForeground(new java.awt.Color(105, 58, 128));
        tf_codigoS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 58, 128), null));
        tf_codigoS.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_codigoS.setDisabledTextColor(new java.awt.Color(105, 58, 128));
        tf_codigoS.setSelectionColor(new java.awt.Color(105, 58, 128));
        tf_codigoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codigoSActionPerformed(evt);
            }
        });

        js_añoS.setModel(new javax.swing.SpinnerNumberModel(1990, 1990, 2024, 10));

        tf_precioS.setForeground(new java.awt.Color(105, 58, 128));
        tf_precioS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 58, 128), null));
        tf_precioS.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_precioS.setDisabledTextColor(new java.awt.Color(105, 58, 128));
        tf_precioS.setSelectionColor(new java.awt.Color(105, 58, 128));
        tf_precioS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_precioSActionPerformed(evt);
            }
        });

        jc_generoS.setForeground(new java.awt.Color(96, 39, 125));
        jc_generoS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "romance ", "terror ", "suspenso ", "comedia", "infantil " }));

        jl_StockS.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_StockS.setForeground(new java.awt.Color(96, 39, 125));
        jl_StockS.setText("Cantidad en stock:");

        js_cantStockS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jb_añoS.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jb_añoS.setForeground(new java.awt.Color(96, 39, 125));
        jb_añoS.setText("Año:");

        jl_tituloS.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_tituloS.setForeground(new java.awt.Color(96, 39, 125));
        jl_tituloS.setText("Titulo:");

        jl_precioVentaS.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_precioVentaS.setForeground(new java.awt.Color(96, 39, 125));
        jl_precioVentaS.setText("Precio de venta:");

        jl_codigoS.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_codigoS.setForeground(new java.awt.Color(96, 39, 125));
        jl_codigoS.setText("Codigo ID:");

        tf_nombreS.setForeground(new java.awt.Color(105, 58, 128));
        tf_nombreS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 58, 128), null));
        tf_nombreS.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_nombreS.setDisabledTextColor(new java.awt.Color(105, 58, 128));
        tf_nombreS.setSelectionColor(new java.awt.Color(105, 58, 128));
        tf_nombreS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreSActionPerformed(evt);
            }
        });

        jl_temporadasS.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_temporadasS.setForeground(new java.awt.Color(96, 39, 125));
        jl_temporadasS.setText("Temporadas:");

        js_temporadasS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jl_productoraS.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_productoraS.setForeground(new java.awt.Color(96, 39, 125));
        jl_productoraS.setText("Productora:");

        js_capitulosS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jl_capitulosS.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_capitulosS.setForeground(new java.awt.Color(96, 39, 125));
        jl_capitulosS.setText("Capitullos:");

        tf_productoraS.setForeground(new java.awt.Color(105, 58, 128));
        tf_productoraS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 58, 128), null));
        tf_productoraS.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_productoraS.setDisabledTextColor(new java.awt.Color(105, 58, 128));
        tf_productoraS.setSelectionColor(new java.awt.Color(105, 58, 128));
        tf_productoraS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_productoraSActionPerformed(evt);
            }
        });

        jl_actoresS.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_actoresS.setForeground(new java.awt.Color(96, 39, 125));
        jl_actoresS.setText("Actores principales:");

        ta_actoresS.setColumns(20);
        ta_actoresS.setForeground(new java.awt.Color(105, 58, 128));
        ta_actoresS.setRows(5);
        ta_actoresS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 58, 128), null));
        ta_actoresS.setDisabledTextColor(new java.awt.Color(96, 35, 125));
        ta_actoresS.setSelectionColor(new java.awt.Color(96, 35, 125));
        jScrollPane2.setViewportView(ta_actoresS);

        jb_CancelarS.setBackground(new java.awt.Color(96, 39, 125));
        jb_CancelarS.setFont(new java.awt.Font("Fredoka", 1, 13)); // NOI18N
        jb_CancelarS.setForeground(new java.awt.Color(238, 229, 242));
        jb_CancelarS.setText("Cancelar");

        jb_LimparS.setBackground(new java.awt.Color(96, 39, 125));
        jb_LimparS.setFont(new java.awt.Font("Fredoka", 1, 13)); // NOI18N
        jb_LimparS.setForeground(new java.awt.Color(238, 229, 242));
        jb_LimparS.setText("Limpiar");

        jb_GuardarS.setBackground(new java.awt.Color(96, 39, 125));
        jb_GuardarS.setFont(new java.awt.Font("Fredoka", 1, 13)); // NOI18N
        jb_GuardarS.setForeground(new java.awt.Color(238, 229, 242));
        jb_GuardarS.setText("Guardar");

        javax.swing.GroupLayout jp_seriesLayout = new javax.swing.GroupLayout(jp_series);
        jp_series.setLayout(jp_seriesLayout);
        jp_seriesLayout.setHorizontalGroup(
            jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_seriesLayout.createSequentialGroup()
                .addGroup(jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_seriesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(hobitoSeries))
                    .addGroup(jp_seriesLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_seriesLayout.createSequentialGroup()
                                .addGroup(jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_añoS)
                                    .addComponent(jl_precioVentaS)
                                    .addComponent(jl_generoS)
                                    .addComponent(jl_codigoS)
                                    .addComponent(jl_tituloS))
                                .addGap(31, 31, 31)
                                .addGroup(jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_precioS, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jc_generoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(js_añoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_codigoS, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nombreS, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_seriesLayout.createSequentialGroup()
                                    .addComponent(jl_capitulosS)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(js_capitulosS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_seriesLayout.createSequentialGroup()
                                    .addComponent(jl_temporadasS)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(js_temporadasS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_seriesLayout.createSequentialGroup()
                                    .addComponent(jl_StockS)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(js_cantStockS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_seriesLayout.createSequentialGroup()
                                    .addComponent(jl_actoresS)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_seriesLayout.createSequentialGroup()
                                    .addComponent(jl_productoraS)
                                    .addGap(53, 53, 53)
                                    .addComponent(tf_productoraS, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jp_seriesLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jb_GuardarS, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_LimparS, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_CancelarS, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jp_seriesLayout.setVerticalGroup(
            jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_seriesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(hobitoSeries)
                .addGap(35, 35, 35)
                .addGroup(jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_tituloS)
                    .addComponent(tf_nombreS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_codigoS)
                    .addComponent(tf_codigoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_generoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_generoS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_añoS)
                    .addComponent(js_añoS, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_precioVentaS)
                    .addComponent(tf_precioS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_StockS)
                    .addComponent(js_cantStockS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_temporadasS)
                    .addComponent(js_temporadasS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_capitulosS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_capitulosS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_productoraS)
                    .addComponent(tf_productoraS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_actoresS)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_LimparS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_CancelarS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_GuardarS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        jTabbedPane1.addTab("Series", jp_series);

        jp_canciones.setBackground(new java.awt.Color(238, 229, 242));

        jl_generoC.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_generoC.setForeground(new java.awt.Color(96, 39, 125));
        jl_generoC.setText("Genero:");

        tf_codigoC.setForeground(new java.awt.Color(105, 58, 128));
        tf_codigoC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 58, 128), null));
        tf_codigoC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_codigoC.setDisabledTextColor(new java.awt.Color(105, 58, 128));
        tf_codigoC.setSelectionColor(new java.awt.Color(105, 58, 128));
        tf_codigoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codigoCActionPerformed(evt);
            }
        });

        js_añoC.setModel(new javax.swing.SpinnerNumberModel(1990, 1990, 2024, 1));

        tf_precioC.setForeground(new java.awt.Color(105, 58, 128));
        tf_precioC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 58, 128), null));
        tf_precioC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_precioC.setDisabledTextColor(new java.awt.Color(105, 58, 128));
        tf_precioC.setSelectionColor(new java.awt.Color(105, 58, 128));
        tf_precioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_precioCActionPerformed(evt);
            }
        });

        jc_generoC.setForeground(new java.awt.Color(96, 39, 125));
        jc_generoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pop", "rock", "jazz", "blues", "country", "electrónica", "hip-hop", "funk", "R&B", "reggaetón", "rap", "indie", " ", " " }));

        jl_StockC.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_StockC.setForeground(new java.awt.Color(96, 39, 125));
        jl_StockC.setText("Cantidad en stock:");

        js_noPistaC.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jb_añoC.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jb_añoC.setForeground(new java.awt.Color(96, 39, 125));
        jb_añoC.setText("Año:");

        jl_tituloC.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_tituloC.setForeground(new java.awt.Color(96, 39, 125));
        jl_tituloC.setText("Titulo:");

        jl_codigoC.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_codigoC.setForeground(new java.awt.Color(96, 39, 125));
        jl_codigoC.setText("Codigo ID:");

        jl_precioVentaC.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_precioVentaC.setForeground(new java.awt.Color(96, 39, 125));
        jl_precioVentaC.setText("Precio de venta:");

        tf_nombreC.setForeground(new java.awt.Color(105, 58, 128));
        tf_nombreC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 58, 128), null));
        tf_nombreC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_nombreC.setDisabledTextColor(new java.awt.Color(105, 58, 128));
        tf_nombreC.setSelectionColor(new java.awt.Color(105, 58, 128));
        tf_nombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreCActionPerformed(evt);
            }
        });

        jl_artistaC.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_artistaC.setForeground(new java.awt.Color(96, 39, 125));
        jl_artistaC.setText("Artista/Banda:");

        tf_artistaC.setForeground(new java.awt.Color(105, 58, 128));
        tf_artistaC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 58, 128), null));
        tf_artistaC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_artistaC.setDisabledTextColor(new java.awt.Color(105, 58, 128));
        tf_artistaC.setSelectionColor(new java.awt.Color(105, 58, 128));
        tf_artistaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_artistaCActionPerformed(evt);
            }
        });

        jl_duracionC.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_duracionC.setForeground(new java.awt.Color(96, 39, 125));
        jl_duracionC.setText("Duracion:");

        tf_duracionC.setForeground(new java.awt.Color(105, 58, 128));
        tf_duracionC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 58, 128), null));
        tf_duracionC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_duracionC.setDisabledTextColor(new java.awt.Color(105, 58, 128));
        tf_duracionC.setSelectionColor(new java.awt.Color(105, 58, 128));
        tf_duracionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_duracionCActionPerformed(evt);
            }
        });

        jl_noPistaC.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_noPistaC.setForeground(new java.awt.Color(96, 39, 125));
        jl_noPistaC.setText("Numero de la pista:");

        js_cantStockC.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jb_GuardarC.setBackground(new java.awt.Color(96, 39, 125));
        jb_GuardarC.setFont(new java.awt.Font("Fredoka", 1, 13)); // NOI18N
        jb_GuardarC.setForeground(new java.awt.Color(238, 229, 242));
        jb_GuardarC.setText("Guardar");

        jb_LimparC.setBackground(new java.awt.Color(96, 39, 125));
        jb_LimparC.setFont(new java.awt.Font("Fredoka", 1, 13)); // NOI18N
        jb_LimparC.setForeground(new java.awt.Color(238, 229, 242));
        jb_LimparC.setText("Limpiar");

        jb_CancelarC.setBackground(new java.awt.Color(96, 39, 125));
        jb_CancelarC.setFont(new java.awt.Font("Fredoka", 1, 13)); // NOI18N
        jb_CancelarC.setForeground(new java.awt.Color(238, 229, 242));
        jb_CancelarC.setText("Cancelar");

        javax.swing.GroupLayout jp_cancionesLayout = new javax.swing.GroupLayout(jp_canciones);
        jp_canciones.setLayout(jp_cancionesLayout);
        jp_cancionesLayout.setHorizontalGroup(
            jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cancionesLayout.createSequentialGroup()
                .addGroup(jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_cancionesLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(hobitoCanciones))
                    .addGroup(jp_cancionesLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_cancionesLayout.createSequentialGroup()
                                .addGroup(jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_añoC)
                                    .addComponent(jl_precioVentaC)
                                    .addComponent(jl_generoC)
                                    .addComponent(jl_codigoC)
                                    .addComponent(jl_tituloC))
                                .addGap(31, 31, 31)
                                .addGroup(jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_precioC, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jc_generoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(js_añoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_codigoC, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_cancionesLayout.createSequentialGroup()
                                .addGroup(jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_StockC)
                                    .addComponent(jl_artistaC)
                                    .addComponent(jl_duracionC)
                                    .addComponent(jl_noPistaC))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_artistaC, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(js_noPistaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_duracionC, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(js_cantStockC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jp_cancionesLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jb_GuardarC, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_LimparC, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_CancelarC, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jp_cancionesLayout.setVerticalGroup(
            jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cancionesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(hobitoCanciones)
                .addGap(35, 35, 35)
                .addGroup(jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_tituloC)
                    .addComponent(tf_nombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_codigoC)
                    .addComponent(tf_codigoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_generoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_generoC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_añoC)
                    .addComponent(js_añoC, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_precioVentaC)
                    .addComponent(tf_precioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_StockC)
                    .addComponent(js_cantStockC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_artistaC)
                    .addComponent(tf_artistaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_duracionC)
                    .addComponent(tf_duracionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_noPistaC)
                    .addComponent(js_noPistaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jp_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_LimparC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_CancelarC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_GuardarC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Canciones", jp_canciones);

        jp_peliculas.setBackground(new java.awt.Color(238, 229, 242));
        jp_peliculas.setToolTipText("Peliculas ");

        jl_tituloP.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_tituloP.setForeground(new java.awt.Color(96, 39, 125));
        jl_tituloP.setText("Titulo:");

        jl_codigoP.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_codigoP.setForeground(new java.awt.Color(96, 39, 125));
        jl_codigoP.setText("Codigo ID:");

        jl_generoP.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_generoP.setForeground(new java.awt.Color(96, 39, 125));
        jl_generoP.setText("Genero:");

        js_añoP.setModel(new javax.swing.SpinnerNumberModel(1990, 1990, 2024, 1));

        jc_generoP.setForeground(new java.awt.Color(96, 39, 125));
        jc_generoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "romance ", "terror ", "suspenso ", "comedia", "infantil " }));

        jb_añoP.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jb_añoP.setForeground(new java.awt.Color(96, 39, 125));
        jb_añoP.setText("Año:");

        jl_precioVentaP.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_precioVentaP.setForeground(new java.awt.Color(96, 39, 125));
        jl_precioVentaP.setText("Precio de venta:");

        tf_nombreP.setForeground(new java.awt.Color(105, 58, 128));
        tf_nombreP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 58, 128), null));
        tf_nombreP.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_nombreP.setDisabledTextColor(new java.awt.Color(105, 58, 128));
        tf_nombreP.setSelectionColor(new java.awt.Color(105, 58, 128));
        tf_nombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombrePActionPerformed(evt);
            }
        });

        tf_codigoP.setForeground(new java.awt.Color(105, 58, 128));
        tf_codigoP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 58, 128), null));
        tf_codigoP.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_codigoP.setDisabledTextColor(new java.awt.Color(105, 58, 128));
        tf_codigoP.setSelectionColor(new java.awt.Color(105, 58, 128));
        tf_codigoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codigoPActionPerformed(evt);
            }
        });

        tf_precioP.setForeground(new java.awt.Color(105, 58, 128));
        tf_precioP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 58, 128), null));
        tf_precioP.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_precioP.setDisabledTextColor(new java.awt.Color(105, 58, 128));
        tf_precioP.setSelectionColor(new java.awt.Color(105, 58, 128));
        tf_precioP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_precioPActionPerformed(evt);
            }
        });

        jl_StockP.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_StockP.setForeground(new java.awt.Color(96, 39, 125));
        jl_StockP.setText("Cantidad en stock:");

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jl_DirectorP.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_DirectorP.setForeground(new java.awt.Color(96, 39, 125));
        jl_DirectorP.setText("Director:");

        tf_directorP.setForeground(new java.awt.Color(105, 58, 128));
        tf_directorP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 58, 128), null));
        tf_directorP.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_directorP.setDisabledTextColor(new java.awt.Color(105, 58, 128));
        tf_directorP.setSelectionColor(new java.awt.Color(105, 58, 128));
        tf_directorP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_directorPActionPerformed(evt);
            }
        });

        jl_actoresP.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_actoresP.setForeground(new java.awt.Color(96, 39, 125));
        jl_actoresP.setText("Actores principales:");

        ta_actoresP.setColumns(20);
        ta_actoresP.setForeground(new java.awt.Color(105, 58, 128));
        ta_actoresP.setRows(5);
        ta_actoresP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 58, 128), null));
        ta_actoresP.setDisabledTextColor(new java.awt.Color(96, 35, 125));
        ta_actoresP.setSelectionColor(new java.awt.Color(96, 35, 125));
        jScrollPane1.setViewportView(ta_actoresP);

        jl_duracionP.setFont(new java.awt.Font("Fredoka", 1, 14)); // NOI18N
        jl_duracionP.setForeground(new java.awt.Color(96, 39, 125));
        jl_duracionP.setText("Duracion:");

        tf_duracionP.setForeground(new java.awt.Color(105, 58, 128));
        tf_duracionP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 58, 128), null));
        tf_duracionP.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_duracionP.setDisabledTextColor(new java.awt.Color(105, 58, 128));
        tf_duracionP.setSelectionColor(new java.awt.Color(105, 58, 128));
        tf_duracionP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_duracionPActionPerformed(evt);
            }
        });

        jb_LimparP.setBackground(new java.awt.Color(96, 39, 125));
        jb_LimparP.setFont(new java.awt.Font("Fredoka", 1, 13)); // NOI18N
        jb_LimparP.setForeground(new java.awt.Color(238, 229, 242));
        jb_LimparP.setText("Limpiar");

        jb_GuardarP.setBackground(new java.awt.Color(96, 39, 125));
        jb_GuardarP.setFont(new java.awt.Font("Fredoka", 1, 13)); // NOI18N
        jb_GuardarP.setForeground(new java.awt.Color(238, 229, 242));
        jb_GuardarP.setText("Guardar");

        jb_CancelarP.setBackground(new java.awt.Color(96, 39, 125));
        jb_CancelarP.setFont(new java.awt.Font("Fredoka", 1, 13)); // NOI18N
        jb_CancelarP.setForeground(new java.awt.Color(238, 229, 242));
        jb_CancelarP.setText("Cancelar");

        javax.swing.GroupLayout jp_peliculasLayout = new javax.swing.GroupLayout(jp_peliculas);
        jp_peliculas.setLayout(jp_peliculasLayout);
        jp_peliculasLayout.setHorizontalGroup(
            jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_peliculasLayout.createSequentialGroup()
                .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_peliculasLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(hobitoPeliculas))
                    .addGroup(jp_peliculasLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_peliculasLayout.createSequentialGroup()
                                .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_añoP)
                                    .addComponent(jl_precioVentaP)
                                    .addComponent(jl_generoP)
                                    .addComponent(jl_codigoP)
                                    .addComponent(jl_tituloP))
                                .addGap(37, 37, 37)
                                .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(js_añoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_precioP, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jc_generoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_codigoP, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_peliculasLayout.createSequentialGroup()
                                .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_peliculasLayout.createSequentialGroup()
                                        .addComponent(jl_actoresP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jp_peliculasLayout.createSequentialGroup()
                                        .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jl_StockP)
                                            .addComponent(jl_DirectorP)
                                            .addComponent(jl_duracionP))
                                        .addGap(21, 21, 21)))
                                .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_duracionP, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_directorP, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1))))))
                    .addGroup(jp_peliculasLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jb_GuardarP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_LimparP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_CancelarP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_peliculasLayout.setVerticalGroup(
            jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_peliculasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(hobitoPeliculas)
                .addGap(32, 32, 32)
                .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_tituloP)
                    .addComponent(tf_nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_codigoP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_codigoP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_generoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_generoP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_añoP)
                    .addComponent(js_añoP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_precioVentaP)
                    .addComponent(tf_precioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_StockP)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_DirectorP)
                    .addComponent(tf_directorP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_duracionP)
                    .addComponent(tf_duracionP, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_actoresP)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jp_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_LimparP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_CancelarP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_GuardarP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        jTabbedPane1.addTab("Peliculas", jp_peliculas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_codigoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codigoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_codigoSActionPerformed

    private void tf_precioSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_precioSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_precioSActionPerformed

    private void tf_nombreSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreSActionPerformed

    private void tf_productoraSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_productoraSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_productoraSActionPerformed

    private void tf_codigoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codigoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_codigoCActionPerformed

    private void tf_precioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_precioCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_precioCActionPerformed

    private void tf_nombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreCActionPerformed

    private void tf_artistaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_artistaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_artistaCActionPerformed

    private void tf_duracionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_duracionCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_duracionCActionPerformed

    private void tf_nombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombrePActionPerformed

    private void tf_codigoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codigoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_codigoPActionPerformed

    private void tf_precioPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_precioPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_precioPActionPerformed

    private void tf_directorPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_directorPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_directorPActionPerformed

    private void tf_duracionPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_duracionPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_duracionPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hobitoCanciones;
    private javax.swing.JLabel hobitoPeliculas;
    private javax.swing.JLabel hobitoSeries;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_CancelarC;
    private javax.swing.JButton jb_CancelarP;
    private javax.swing.JButton jb_CancelarS;
    private javax.swing.JButton jb_GuardarC;
    private javax.swing.JButton jb_GuardarP;
    private javax.swing.JButton jb_GuardarS;
    private javax.swing.JButton jb_LimparC;
    private javax.swing.JButton jb_LimparP;
    private javax.swing.JButton jb_LimparS;
    private javax.swing.JLabel jb_añoC;
    private javax.swing.JLabel jb_añoP;
    private javax.swing.JLabel jb_añoS;
    private javax.swing.JComboBox<String> jc_generoC;
    private javax.swing.JComboBox<String> jc_generoP;
    private javax.swing.JComboBox<String> jc_generoS;
    private javax.swing.JLabel jl_DirectorP;
    private javax.swing.JLabel jl_StockC;
    private javax.swing.JLabel jl_StockP;
    private javax.swing.JLabel jl_StockS;
    private javax.swing.JLabel jl_actoresP;
    private javax.swing.JLabel jl_actoresS;
    private javax.swing.JLabel jl_artistaC;
    private javax.swing.JLabel jl_capitulosS;
    private javax.swing.JLabel jl_codigoC;
    private javax.swing.JLabel jl_codigoP;
    private javax.swing.JLabel jl_codigoS;
    private javax.swing.JLabel jl_duracionC;
    private javax.swing.JLabel jl_duracionP;
    private javax.swing.JLabel jl_generoC;
    private javax.swing.JLabel jl_generoP;
    private javax.swing.JLabel jl_generoS;
    private javax.swing.JLabel jl_noPistaC;
    private javax.swing.JLabel jl_precioVentaC;
    private javax.swing.JLabel jl_precioVentaP;
    private javax.swing.JLabel jl_precioVentaS;
    private javax.swing.JLabel jl_productoraS;
    private javax.swing.JLabel jl_temporadasS;
    private javax.swing.JLabel jl_tituloC;
    private javax.swing.JLabel jl_tituloP;
    private javax.swing.JLabel jl_tituloS;
    private javax.swing.JPanel jp_canciones;
    private javax.swing.JPanel jp_peliculas;
    private javax.swing.JPanel jp_series;
    private javax.swing.JSpinner js_añoC;
    private javax.swing.JSpinner js_añoP;
    private javax.swing.JSpinner js_añoS;
    private javax.swing.JSpinner js_cantStockC;
    private javax.swing.JSpinner js_cantStockS;
    private javax.swing.JSpinner js_capitulosS;
    private javax.swing.JSpinner js_noPistaC;
    private javax.swing.JSpinner js_temporadasS;
    private javax.swing.JTextArea ta_actoresP;
    private javax.swing.JTextArea ta_actoresS;
    private javax.swing.JTextField tf_artistaC;
    private javax.swing.JTextField tf_codigoC;
    private javax.swing.JTextField tf_codigoP;
    private javax.swing.JTextField tf_codigoS;
    private javax.swing.JTextField tf_directorP;
    private javax.swing.JTextField tf_duracionC;
    private javax.swing.JTextField tf_duracionP;
    private javax.swing.JTextField tf_nombreC;
    private javax.swing.JTextField tf_nombreP;
    private javax.swing.JTextField tf_nombreS;
    private javax.swing.JTextField tf_precioC;
    private javax.swing.JTextField tf_precioP;
    private javax.swing.JTextField tf_precioS;
    private javax.swing.JTextField tf_productoraS;
    // End of variables declaration//GEN-END:variables
}
