CREATE DATABASE POO_MUSICA;
USE POO_MUSICA;
CREATE TABLE ALBUMES (
    ID_ALBUM VARCHAR(16) PRIMARY KEY,
    NOMBRE_ALBUM VARCHAR(100),
    FECHA_LANZAMIENTO VARCHAR(16)
);
CREATE TABLE PISTAS(
    ID_PISTA VARCHAR(16) PRIMARY KEY,
    TIPO_PISTA VARCHAR(20),
    NOMBRE_ARTISTA VARCHAR(25),
    ID_ALBUM VARCHAR(16) NOT NULL,
    SELLO_DISCOGRAFICO VARCHAR(25),
    FORMATO VARCHAR(16),
    EDICION VARCHAR(12),
    FOREIGN KEY (ID_ALBUM) REFERENCES ALBUMES (ID_ALBUM)
);
CREATE TABLE PELICULAS_SERIES (
    ID_PELICULA_SERIE VARCHAR(16) PRIMARY KEY,
    TITULO VARCHAR(150),
    GENERO VARCHAR(50),
    ANIO_ESTRENO INT,
    FORMATO VARCHAR(10) DEFAULT 'MP4',
    DIRECTOR VARCHAR(16),
    PRODUCTORA VARCHAR(16),
    ID_ALBUM_SOUNDTRACK VARCHAR(16) NOT NULL, -- opcional
    FOREIGN KEY (ID_ALBUM_SOUNDTRACK) REFERENCES ALBUMES(ID_ALBUM)
);
-- Tabla de usuarios o clientes
CREATE TABLE USUARIOS (
    ID_USUARIO VARCHAR(16) PRIMARY KEY,
    NOMBRE_COMPLETO VARCHAR(100),
    CORREO_ELECTRONICO VARCHAR(100) UNIQUE
);

-- Tabla de compras (historial)
CREATE TABLE COMPRAS (
    ID_COMPRA VARCHAR(16) PRIMARY KEY,
    ID_USUARIO VARCHAR(16),
    FECHA_COMPRA VARCHAR(25),
    COMPROBANTE_URL VARCHAR(100), -- ruta o enlace al archivo PDF/imagen
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

-- Tabla de gestión de enlaces de descarga
CREATE TABLE ENLACES_DESCARGA (
    ID_ENLACE VARCHAR(16) PRIMARY KEY,
    ID_COMPRA VARCHAR(16),
    ENLACE_GENERADO VARCHAR(100),
    FECHA_GENERACION VARCHAR(50) ,
    ESTADO_DESCARGA BOOLEAN DEFAULT FALSE, -- TRUE si ya fue descargado
    FECHA_EXPIRACION VARCHAR(50),
    PENALIZACION VARCHAR(100), -- puede ser un texto explicativo
    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRAS(ID_COMPRA)
);


