/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.gui;

import java.awt.BorderLayout;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import model.Album;

/**
 *
 * @author cybergato
 */
public class TarjetaAlbum extends javax.swing.JPanel {

    /**
     * Creates new form TarjetaAlbum
     */
    public TarjetaAlbum(Album album) {
        initComponents();
        nombreAlbumLbl.setText(album.getNombreAlbum());
        nombreArtistaLbl.setText(album.getArtista());
        anoLbl.setText(album.getFecha_lanzamiento());

        // Cargar imagen
        if (album.getUrlIcon() != null && !album.getUrlIcon().isEmpty()) {
            SwingUtilities.invokeLater(() -> {
                try {
                    URL url = new URL(album.getUrlIcon());
                    ImageIcon icon = new ImageIcon(url);
                    Image img = icon.getImage().getScaledInstance(
                            imagenIconContainer.getWidth() > 0 ? imagenIconContainer.getWidth() : 100,
                            imagenIconContainer.getHeight() > 0 ? imagenIconContainer.getHeight() : 100,
                            Image.SCALE_SMOOTH
                    );

                    JLabel imgLabel = new JLabel(new ImageIcon(img));
                    imgLabel.setHorizontalAlignment(SwingConstants.CENTER);
                    imgLabel.setVerticalAlignment(SwingConstants.CENTER);

                    imagenIconContainer.setLayout(new BorderLayout());
                    imagenIconContainer.add(imgLabel, BorderLayout.CENTER);
                    imagenIconContainer.revalidate();
                    imagenIconContainer.repaint();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }

        // Refrescar panel
        imagenIconContainer.revalidate();
        imagenIconContainer.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAlbum = new javax.swing.JPanel();
        imagenIconContainer = new javax.swing.JPanel();
        nombreAlbumLbl = new javax.swing.JLabel();
        nombreArtistaLbl = new javax.swing.JLabel();
        anoLbl = new javax.swing.JLabel();

        javax.swing.GroupLayout imagenIconContainerLayout = new javax.swing.GroupLayout(imagenIconContainer);
        imagenIconContainer.setLayout(imagenIconContainerLayout);
        imagenIconContainerLayout.setHorizontalGroup(
            imagenIconContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        imagenIconContainerLayout.setVerticalGroup(
            imagenIconContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        nombreAlbumLbl.setText("Nombre del album");

        nombreArtistaLbl.setText("Nombre del artista");

        anoLbl.setText("Año de creacion");

        javax.swing.GroupLayout panelAlbumLayout = new javax.swing.GroupLayout(panelAlbum);
        panelAlbum.setLayout(panelAlbumLayout);
        panelAlbumLayout.setHorizontalGroup(
            panelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlbumLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(imagenIconContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreAlbumLbl)
                    .addComponent(anoLbl)
                    .addComponent(nombreArtistaLbl))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelAlbumLayout.setVerticalGroup(
            panelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlbumLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagenIconContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAlbumLayout.createSequentialGroup()
                        .addComponent(nombreAlbumLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreArtistaLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(anoLbl)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anoLbl;
    private javax.swing.JPanel imagenIconContainer;
    private javax.swing.JLabel nombreAlbumLbl;
    private javax.swing.JLabel nombreArtistaLbl;
    private javax.swing.JPanel panelAlbum;
    // End of variables declaration//GEN-END:variables
}
